version: "3"
   
services:
  
  web1:
    container_name: web1
    build: backend
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
      - "8000:8000"
    volumes: 
      - ./backend/LearnApp:/LearnApp
  
    
  
  angular:
    container_name: angular
    build: frontend
    ports:
      - "80:80"
